In [1]:
import pandas as pd

In [2]:
data  = pd.read_csv("car_data.csv")

In [3]:
data.shape

(892, 6)

In [4]:
data.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

# Data Cleaning
    - Missing Values
           Drop
         - Drop the records having missing data
         - Drop the columns having missing data
           Fill 
         - Fill the missing values
               - Hard coded value
               - Calculated Values
               - Following or Preceding 
    - Duplicate Records
    - Outlier

# Missing Values: isna()   isnull()

In [6]:
data.isna().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [7]:
data['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [8]:
data['kms_driven'].isna().sum()
# data['kms_driven']

np.int64(52)

#### Drop all the missing records

In [9]:
# dropping rows that have missing values
data.dropna(axis=0)   # horizontal

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,"2,70,000","50,000 kms",Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,"1,10,000","30,000 kms",Diesel
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel

In [10]:
# dropping columns that have missing values
data.dropna(axis=1) # vertical

                                       name    company  year          Price
0      Hyundai Santro Xing XO eRLX Euro III    Hyundai  2007         80,000
1                   Mahindra Jeep CL550 MDI   Mahindra  2006       4,25,000
2                Maruti Suzuki Alto 800 Vxi     Maruti  2018  Ask For Price
3    Hyundai Grand i10 Magna 1.2 Kappa VTVT    Hyundai  2014       3,25,000
4          Ford EcoSport Titanium 1.5L TDCi       Ford  2014       5,75,000
..                                      ...        ...   ...            ...
887                                      Ta       Tara  zest       3,10,000
888                     Tata Zest XM Diesel       Tata  2018       2,60,000
889                      Mahindra Quanto C8   Mahindra  2013       3,90,000
890                Honda Amaze 1.2 E i VTEC      Honda  2014       1,80,000
891               Chevrolet Sail 1.2 LT ABS  Chevrolet  2014       1,60,000

[892 rows x 4 columns]

In [11]:
# drop only those records where all the values are missing
data.dropna(how='all',axis=0)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [12]:
# drop all the records where any of the values are missing
data.dropna(how='any',axis=0)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,"2,70,000","50,000 kms",Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,"1,10,000","30,000 kms",Diesel
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel

In [13]:
int(data.shape[1]*.70)

4

In [14]:
int(data.shape[1]*.70)

4

In [15]:
# retain all the records where at least 70% value are valid
data.dropna(axis=0, thresh=int(data.shape[1]*.70))

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [16]:
# retain all the records where at least 70% value are valid
data.dropna(axis=1, thresh=int(data.shape[0]*.70))

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [17]:
# drop all those records where any value missing in year price or kms_driven
data.dropna(axis=0, subset=['year','Price','kms_driven'])

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [18]:
# drop all those records where ALL value missing in year price or kms_driven
data.dropna(axis=0, subset=['year','Price','kms_driven'],how='all')

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

# Filling Missing Data

In [19]:
# fill all the missing value with ahardcoded value like 0 we did, 
data.fillna(0)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",0,0
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,0
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,0

# Filling missing data using mean , median , mode , min , max

In [20]:
sum((19,23,1,3,53))/5

19.8

##### Central Tendency
           - if there is outlier in data we will use median
           - if there is not outlier in data we will use mean
           - for categorical e will use mode
##### Bfill(), ffill()

In [21]:
import numpy as np
ages = np.array([14,15,14,15,16,18,19,20,21,23,90,84])
ages

array([14, 15, 14, 15, 16, 18, 19, 20, 21, 23, 90, 84])

In [23]:
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [24]:
sns.boxplot(ages)

NameError: name 'sns' is not defined

In [25]:
data.fuel_type.unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [26]:
data.fuel_type.isna().sum()

np.int64(55)

In [27]:
data.fuel_type.value_counts()

fuel_type
Petrol    440
Diesel    395
LPG         2
Name: count, dtype: int64

In [28]:
data.fuel_type.value_counts(dropna=False)

fuel_type
Petrol    440
Diesel    395
NaN        55
LPG         2
Name: count, dtype: int64

In [29]:
mode_value = data.fuel_type.mode()[0]
mode_value

'Petrol'

In [30]:
data.fuel_type.fillna(mode_value)

0      Petrol
1      Diesel
2      Petrol
3      Petrol
4      Diesel
        ...
887    Petrol
888    Diesel
889    Diesel
890    Petrol
891    Petrol
Name: fuel_type, Length: 892, dtype: object

In [31]:
# data.fuel_type = data.fuel_type.fillna(data.fuel_type.mode()[0])

In [32]:
data.fuel_type.isna().sum()

np.int64(55)

In [33]:
data.kms_driven.isna().sum()

np.int64(52)

In [34]:
# data.kms_driven.dropna()
data.kms_driven.apply(lambda x: x.replace(' kms', ''))

AttributeError: 'float' object has no attribute 'replace'

In [35]:
data.kms_driven = data.kms_driven.str.replace(' kms','').str.replace(',', '')

In [36]:
data.kms_driven.astype(float)

ValueError: could not convert string to float: 'Petrol'

In [ ]:
data = data.dropna(subset=['kms_driven'])

In [ ]:
data.kms_driven

0       45000
1          40
2       22000
3       28000
4       36000
        ...
883     50000
885     30000
886    132000
888     27000
889     40000
Name: kms_driven, Length: 838, dtype: object

In [ ]:
data.kms_driven = data.kms_driven.astype(float)
data.kms_driven

C:\Users\SMIT\AppData\Local\Temp\ipykernel_9828\3263063546.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.kms_driven = data.kms_driven.astype(float)

0       45000.0
1          40.0
2       22000.0
3       28000.0
4       36000.0
         ...
883     50000.0
885     30000.0
886    132000.0
888     27000.0
889     40000.0
Name: kms_driven, Length: 838, dtype: float64

In [37]:
data = data[data.Price != 'Ask For Price']

In [38]:
data.Price = data.Price.str.replace(',', '').astype(float)

In [39]:
data.Price

0       80000.0
1      425000.0
3      325000.0
4      575000.0
6      175000.0
         ...
887    310000.0
888    260000.0
889    390000.0
890    180000.0
891    160000.0
Name: Price, Length: 857, dtype: float64

In [40]:
data.year = data.year.astype(int)

ValueError: invalid literal for int() with base 10: '150k'

In [ ]:
data.year.unique()

array([2007, 2006, 2014, 2012, 2013, 2016, 2015, 2010, 2017, 2008, 2018,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001])

In [ ]:
data.dropna(subset=['fuel_type'], inplace=True)

In [41]:
data.fuel_type.value_counts(dropna=False)

fuel_type
Petrol    428
Diesel    386
NaN        41
LPG         2
Name: count, dtype: int64

In [42]:
data.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000.0,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000.0,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000.0,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000.0,36000,Diesel
6,Ford Figo,Ford,2012,175000.0,41000,Diesel

In [43]:
data.to_csv('cleaned_data.csv')

In [44]:
# ignore all lines below this one, class end

In [ ]:
dd# it will not work, bcz we have a string value in the data that can not be converted into float {petrol}
data.kms_driven.str.replace("kms","").str.replace(",",'').astype(float)

In [ ]:
# check hom many value where kms are petrol
data[data.kms_driven=='Petrol']

In [ ]:
data.kms_driven.replace('Petrol', "0", inplace=True)

In [ ]:
# petrol is treplaced by 0 and kms can be converted into float now
data.kms_driven = data.kms_driven.str.replace("kms","").str.replace(",",'').astype(float)

In [ ]:
#we need to fill NAN value
data.kms_driven.isna().sum()

In [ ]:
sns.boxplot(data.kms_driven)

In [ ]:
data.kms_driven = data.kms_driven.fillna(data.kms_driven.median())

In [ ]:
data.kms_driven.isna().sum()

In [ ]:
data.kms_driven.replace('0',data.kms_driven.median(),inplace=True)

In [ ]:
data.isna().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     1
dtype: int64

In [ ]:
data.Price.isna().sum()

0

In [ ]:
data[data.Price=="Ask For Price"]

In [ ]:
data.Price.replace("Ask For Price",0,inplace=True)

In [ ]:
data.Price.replace(0,"0",inplace=True)

In [ ]:
data[data.Price==0].shape

In [ ]:
data.Price.isna().sum()

In [ ]:
data.Price  = data.Price.str.replace(",",'').astype(int)

In [ ]:
data.Price.replace(0, data.Price.median(),inplace=True)

In [ ]:
data.year.unique()

In [ ]:
new_data  = data[data.year.str.isnumeric()]

In [ ]:
new_data.year.unique()

In [ ]:
new_data.year = new_data.year.astype(int)

In [ ]:
new_data.head()

In [ ]:
data_with_wrong_years = data[~(data.year.str.isnumeric())]

In [ ]:
new_data.info()

In [ ]:
new_data.to_csv('cleaned_data.csv')