In [4]:
print(5 ** 2 + 6 / 3 )

27.0

In [5]:
print(5 ** 2 + 6 / 3)

27.0

In [6]:
print(((5 ** 2)+ 6)/ 3)

10.333333333333334

In [7]:
x = "Python"
y = "Programming"
print(x,y)

Python Programming

In [9]:
print(x + ' ' + y)

Python Programming

x = 'hello'

In [10]:
print(type(x))

<class 'str'>

In [11]:
y = 12.5

In [12]:
print(type(y))

<class 'float'>

In [1]:
x = (input('Enter first number'))
y = (input('Enter second number'))
z = (input('Enter third number'))

Enter first number 6
Enter second number 8
Enter third number 4

In [3]:
(type(x))

int

In [4]:
(type(y))

int

In [5]:
(type(z))

int

In [6]:
print(x + y + z)

18

In [7]:
(id(x))

140720770827208

In [8]:
(id(y))

140720770827272

In [9]:
(id(z))

140720770827144

In [10]:
n = (input('Enter your full name'))

Enter your full name Abdul Haseeb

In [11]:
(n.upper())

'ABDUL HASEEB'

In [12]:
(n.lower())

'abdul haseeb'

In [20]:
a = int(input('Enter a number'))
b = int(input('Enter a number'))

Enter a number 7
Enter a number 4

In [21]:
print(a + b)

11

In [22]:
print(a * b)

28

In [24]:
print(a / b)

1.75

In [25]:
print(a // b)

1

In [26]:
print(a % b)

3

In [27]:
print(a - b)

3

In [1]:
print('Abdul Haseeb')

Abdul Haseeb

In [3]:
print('My age is "16"')

My age is "16"

In [4]:
print('Python is fun!')

Python is fun!

In [5]:
print('Ali','Khan',21,True,sep ='\n')

Ali
Khan
21
True

In [6]:
N1 = 20
N2 = 10

In [7]:
print(N1 + N2)

30

In [8]:
print(N1 - N2)

10

In [9]:
print(N1 * N2)

200

In [10]:
print(N1 / N2)

2.0

In [ ]:
#sets

In [1]:
result = {'Eng' : 91,'Math' : 87,'Urdu' : 95,'Comp' : 85,'Phy' : 80}

In [4]:
print(id(result))

3061009195904

In [3]:
type(result)

dict

In [5]:
result.clear()

In [6]:
result

{}

In [7]:
result = {'Eng' : 91,'Math' : 87,'Urdu' : 95,'Comp' : 85,'Phy' : 80}

In [8]:
result.copy()

{'Eng': 91, 'Math': 87, 'Urdu': 95, 'Comp': 85, 'Phy': 80}

In [11]:
marks = result.fromkeys(result, 96)

In [12]:
result

{'Eng': 91, 'Math': 87, 'Urdu': 95, 'Comp': 85, 'Phy': 80}

In [15]:
result = {'Eng' : 91,'Math' : 87,'Urdu' : 95,'Comp' : 85,'Phy' : 80}

In [17]:
new_dict = dict.fromkeys(result, 98)

In [18]:
new_dict

{'Eng': 98, 'Math': 98, 'Urdu': 98, 'Comp': 98, 'Phy': 98}

In [19]:
result = {'Eng' : 91,'Math' : 87,'Urdu' : 95,'Comp' : 85,'Phy' : 80}

### LIST

In [1]:
numbers = [10, 20, 30, 40, 50]

In [2]:
numbers.append(60)

In [3]:
numbers

[10, 20, 30, 40, 50, 60]

In [6]:
numbers.pop(2)

30

In [7]:
numbers

[10, 20, 40, 50, 60]

In [8]:
numbers.reverse()

In [9]:
numbers

[60, 50, 40, 20, 10]

### TUPLE

In [10]:
fruits = ('apple', 'banana', 'cherry', 'mango')

In [11]:
fruits.index('mango')

3

In [12]:
fruit_list = list(fruits)

In [14]:
print(fruit_list)

['apple', 'banana', 'cherry', 'mango']

In [15]:
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6,}

In [16]:
set1.union(set2)

{1, 2, 3, 4, 5, 6}

In [18]:
set1.intersection(set2)

{3, 4}

In [21]:
set1.difference(set2)

{1, 2}

In [22]:
marks = {'math': 90, 'science': 85, 'english': 88}

In [27]:
marks['history']= 75

In [28]:
marks

{'math': 90, 'science': 85, 'english': 88, 'history': 75}

In [29]:
marks['science'] = 95

In [30]:
marks

{'math': 90, 'science': 95, 'english': 88, 'history': 75}

In [31]:
marks.keys()

dict_keys(['math', 'science', 'english', 'history'])

In [2]:
marks.values()

NameError: name 'marks' is not defined

In [8]:
num1 = int(input('Enter the first number'))
num2 = int(input('Enter the second number'))

if num1 < num2:
    print(f'Num1 is "{num1}" which is less than Num2 "{num2}"')

Enter the first number 12
Enter the second number 13

Num1 is "12" which is less than Num2 "13"

In [9]:
num1 < num2

True

In [14]:
False or True

True

In [15]:
num1 = int(input('Enter the first number'))
num2 = int(input('Enter the second number'))

if num1 > num2:
    print(f'{num1} is greater than {num2}')

else:
    print(f'{num1} is less than {num2}')

num1 > num2

Enter the first number 15
Enter the second number 23

15 is less than 23

False

In [19]:
num = int(input('Enter the first number'))

if num % 2 == 0:
    print('This number is even')

else:
    print('This number is odd')

Enter the first number 3

This number is odd

In [23]:
num = float(input('Enter the number'))

if num > 0:
    print('number is positive')

elif num < 0: 
    print('number is negative')

else:
    print('Zero')

Enter the number 0.4

number is positive

In [24]:
a = int(input('Enter a number'))
b = int(input('Enter a number'))
c = int(input('Enter a number'))

smallest = min(a, b, c)
print(f'The smallest number is {smallest}')

Enter a number 854
Enter a number 438
Enter a number 576

The smallest number is 438

In [27]:
num = int(input('Enter the number'))

if num % 5 == 0:
    print(f'The number {num} is divisible by "5"')

else:
    print(f'The number {num} is divisible by "5"')

Enter the number 35

The number 35 is divisible by "5"

In [33]:
students = ['hasan', 'hassaan', 'munsif', 'abdullah', 'haseeb', 'sameel', 'saad', 'arsam', 'darim', 'irfan', 'khubaab']
Student_Name = input('Enter your name')

if Student_Name in students:
    print(f'{Student_Name} you are from students')

else:
    print(f'{Student_Name} you are not from students')

Enter your name haseeb

haseeb you are from students

In [36]:
details = {
    'name': 'Abdul Haseeb',
    'age': 16,
    'qualification': 'Matric',
    'course': 'python',
}

Name = input('Enter your name')
age = int(input('Enter your age'))
qualification = input('Enter your qualification')
course = input('Enter your course')

if (Name == details['name']) and (age == details['age']) and (qualification == details['qualification']) and (course == details['course']):
    print(f'{Name} You are the student of this class')

else:
    print(f'{Name} you are not able to attend the class')

Enter your name Abdul Haseeb
Enter your age 16
Enter your qualification Matric
Enter your course python

Abdul Haseeb You are the student of this class

In [4]:
marks = float(input('Enter your marks: '))

if marks >= 85:
    print('Your grade is "A1", you are passed')
elif 75 <= marks <85:
    print('Your grade is "A", you are passed')
elif 60 <= marks <70:
    print('Your grade is "B", you are passed')
elif 50 <= marks <60:
    print('Your grade is "C", you are passed')
elif 40 <= marks <50:
    print('Your grade is "D", you are passed')
else:
    print("Please Try Again")

Enter your marks:  20

Please Try Again

### want: 
- Car

### REUIREMENTS:
- car
- 1300 cc
- black
- 2025
- new
- toyota

In [14]:
vehicle = input('kiya chahiye')
if vehicle == 'car':
    cc = input('kitni cc car chahiye? ')
    
    if cc == '1300':
        color = input('konsa color ki chahiye? ')
        
        if color == 'black':
            model = input('konse model ki chahiye? ')
            
            if model == '2025':
                condition = input('new chahiye ya purani? ')
                
                if condition == 'new':
                    company = input('konsi company ki? ')
                    if company == 'toyota':
                        print('Ok , Done')
                        
                    else:
                        print('Nahi toyota ki hi chahiye')
                    
                else:
                    print('Nahi new hi chahiye')
                
            else:
                print('Nahi 2025 ka hi chahiye')
            
        else:
            print('Nahi black hi chahiye')
        
    else: 
        print('Nahi mujhe 1300 cc hi chahiye')

else:
    print('mujhe car hi chahiye')

kiya chahiye car
kitni cc car chahiye?  1300
konsa color ki chahiye?  black
konse model ki chahiye?  2025
new chahiye ya purani?  new
konsi company ki?  toyota

Ok , Done

### LOOP

In [3]:
for i in range(1, 6):
    print(f'{i}. Abdul Haseeb')

1. Abdul Haseeb
2. Abdul Haseeb
3. Abdul Haseeb
4. Abdul Haseeb
5. Abdul Haseeb

In [4]:
countries = ['pakistan', 'india', 'iran', 'iraq', 'china', 'afghanistan']

In [5]:
for country in countries:
    print(country)

pakistan
india
iran
iraq
china
afghanistan

In [6]:
for country in countries:
    if len(country) < 5:
        print(country)

iran
iraq

In [7]:
for country in countries:
    if len(country) > 4:
        print(country)

pakistan
india
china
afghanistan

In [8]:
for country in countries:
    if country.endswith('a'):
        print(country)

india
china

In [4]:
countries = ['London', 'Pakistan', 'India', 'China', 'Iran']

In [8]:
for country in countries:
    lower_country = country.lower()
    for char in lower_country:
        if lower_country.count(char) != 1:
            break
    else:
        print(country)

China
Iran

In [9]:
fruits = ['apple', 'mango', 'banana', 'grapes']

In [12]:
for fruit in fruits:
    for char in fruit:
        if fruit.count(char) != 1:
            break
    else:
        print(fruit)

mango
grapes

In [13]:
students = ['ali', 'raheel', 'mohib', 'harshil', 'daniyal']

In [15]:
for student in students:
    for char in student:
        if student.count(char) != 1:
            break
    else:
        print(student)

ali
mohib

In [18]:
foods = ['biryani', 'qorma', 'nihari', 'zarda', 'rabdi']

In [20]:
for food in foods:
    for char in food:
        if food.count(char) != 1:
            break
    else:
        print(food)

qorma
rabdi

In [22]:
names = ['haseeb', 'mohib', 'harshil', 'daniyal', 'anas', 'hadi']

for name in names:
    for char in name:
        if name.count(char) != 1:
            break
    else:
        print(name)

mohib
hadi

In [26]:
for name in names:
    if len(name) < 5:
        print(name)

anas
hadi

In [27]:
games = ['Gta', 'CS', 'IGI', 'Cricket07', 'Cricket07']

In [28]:
for game in games:
    if games.count(game) == 2:
        print(game)

Cricket07
Cricket07

In [29]:
for game in games:
    if games.count(game) == 2:
        print(game)
        break

Cricket07

In [30]:
names = ['haseeb', 'mohib', 'hadi', 'harshil', 'haseeb']

In [32]:
for name in names:
    if names.count(name) == 2:
        print(name)

haseeb
haseeb

In [33]:
for name in names:
    if names.count(name) == 2:
        print(name)
        break

haseeb

In [34]:
for name in names:
    if len(name) < 5:
        print(name)

hadi

In [35]:
for name in names:
    if len(name) > 4:
        print(name)

haseeb
mohib
harshil
haseeb

In [38]:
for name in names:
    if len(name) > 4:
        print(name)

haseeb
mohib
harshil
haseeb

In [39]:
for i in range(3):
    for j in range(2):
        print(i, j)

0 0
0 1
1 0
1 1
2 0
2 1

In [4]:
games = ['Gta', 'CS', 'Criclet07', 'IG', 'CS', 'Cricket07']

In [5]:
for game in games:
    if games.count(game) == 2:
        print(game)

CS
CS

In [6]:
count = 1
while count <= 5:
    print(count)
    count += 1

1
2
3
4
5

In [7]:
games = ['Gta', 'CS', 'IGI', 'Cricket07', 'CS', 'Cricket07']

duplicates = []

for game in games:
    if games.count(game) > 1 and game not in duplicates:
        duplicates.append(game)

for game in duplicates:
    print(game)

CS
Cricket07

In [3]:
def separate_positive_negative(numbers):
    positive = []
    negative = []
    
    for num in numbers:
        if num >= 0:
            positive.append(num)
        else:
            negative.append(num)
    
    print("Positive Numbers:", positive)
    print("Negative Numbers:", negative)

numbers = [-10, 3, -2, 7, -8, 5, 0, -6, 4]
separate_positive_negative(numbers)

Positive Numbers: [3, 7, 5, 0, 4]
Negative Numbers: [-10, -2, -8, -6]

In [8]:
numbers = [-10, 3, -2, 7, -8, 5, 0, -6, 4]

def seperate_positive_negative(numbers):
    positive = []
    negative = []

    for num in numbers:
        if num >= 0:
            positive.append(num)
        else:
            negative.append(num)
    print(positive)
    print(negative)

In [9]:
seperate_positive_negative(numbers)

[3, 7, 5, 0, 4]
[-10, -2, -8, -6]

In [13]:
numbers = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 17, 19, 23, 256, -8, -4, -2, 5, -9]

def check_even_odd(words):
    even = []
    odd = []
    for num in words:
        if num % 2 == 0:
            even.append(num)
        else:
            odd.append(num)
    print(even)
    print(odd)

In [14]:
check_even_odd(numbers)

[2, 4, 6, 8, 10, 256, -8, -4, -2]
[3, 5, 7, 9, 11, 13, 17, 19, 23, 5, -9]

In [15]:
numbers = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 17, 19, 23, 256, -8, -4, -2, 5, -9]

def even_odd_numbers(numbers):
    even = []
    odd = []
    for num in numbers:
        if num % 2 == 0:
            even.append(num)
        else:
            odd.append(num)
    print(even)
    print(odd)

In [16]:
even_odd_numbers(numbers)

[2, 4, 6, 8, 10, 256, -8, -4, -2]
[3, 5, 7, 9, 11, 13, 17, 19, 23, 5, -9]

In [17]:
numbers = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 17, 19, 23, 256, -8, -4, -2, 5, -9]

even = [num for num in numbers if num % 2 == 0]
odd = [num for num in numbers if num % 2 != 0]

print(even)
print(odd)

[2, 4, 6, 8, 10, 256, -8, -4, -2]
[3, 5, 7, 9, 11, 13, 17, 19, 23, 5, -9]

In [18]:
numbers = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 17, 19, 23, 256, -8, -4, -2, 5, -9]

even = [num for num in numbers if num % 2 == 0]
odd = [num for num in numbers if num % 2 != 0]

print(even)
print(odd)

[2, 4, 6, 8, 10, 256, -8, -4, -2]
[3, 5, 7, 9, 11, 13, 17, 19, 23, 5, -9]

In [1]:
numbers = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 17, 19, 23, 256, -8, -4, -2, 5, -9]

divisible_num = [num for num in numbers if num % 3 == 0]
not_divisible_num = [num for num in numbers if num % 3 != 0] 

print(divisible_num)
print(not_divisible_num)

[3, 6, 9, -9]
[2, 4, 5, 7, 8, 10, 11, 13, 17, 19, 23, 256, -8, -4, -2, 5]

In [2]:
numbers = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 17, 19, 23, 256, -8, -4, -2, 5, -9]

numb = [num for num in numbers if num / 1 == num]

print(numb)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 17, 19, 23, 256, -8, -4, -2, 5, -9]

In [11]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]

divisible_by_three = [num for num in numbers if num % 3 == 0]
divisible_by_five = [num for num in numbers if num % 5 == 0]

print(divisible_by_three)
print(divisible_by_five)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]

In [5]:
def addition(a, b):
    c = a + b
    return c

In [6]:
addition(2, 5)

7

In [8]:
def multiply(a, b):
    return a * b

multiply(3, 4)

12

In [11]:
def power(a, b):
    return a ** b

power(3, 3)

27

In [14]:
def is_even(num):
    if num%2==0:
        return "True"
    else:
        return "False"

is_even(5)

'False'

In [17]:
def factorial(a):
    total = 1
    for n in range (a,0,-1):
        total *= n
    return total

factorial(5)

120

In [19]:
def factorial(a):
    total = 1
    for n in range(a,0,-1):
        total *= n
    return total

factorial(7)

5040

In [1]:
def fahrenheit_to_celcius(fahrenheit):
    return (fahrenheit-32)*5/9

In [2]:
fahrenheit_to_celcius(32)

0.0

In [3]:
def celcius_to_fahrenheit(celcius):
    return (celcius*9/5)+32

In [4]:
celcius_to_fahrenheit(32)

89.6

In [6]:
def celcius_to_fahrenheit(celcius):
    return (celcius*9/5)+32

def fahrenheit_to_celcius(fahrenheit):
    return (fahrenheit-32)*5/9

print("Temperature converter:")
print("1.Celcius to fahrenheit")
print("2.Fahrenheit to celcius")

choice = input("Enter 1 or 2")

if choice == '1':
    c = float(input("Enter temperature in celcius: "))
    f =  celcius_to_fahrenheit(c)
    print(f"{c} C = {f} F")

elif choice == '2':
    f = float(input("Enter temperature in fahrenheit: "))
    c = fahrenheit_to_celcius(f)
    print(f"{f} F = {c} C")

else:
    print("Invalid Choice")

Temperature converter:
1.Celcius to fahrenheit
2.Fahrenheit to celcius

Enter 1 or 2 1
Enter temperature in celcius:  3532

3532.0 C = 6389.6 F

In [1]:
def celcius_to_fahrenheit(celcius):
    return(celcius*9/5)+32

def fahrenheit_to_celcius(fahrenheit):
    return (fahrenheit-32)*5/9

print("Temperature Converter")
print("1.Celcius to fahrenheit")
print("2.Fahrenheit to celcius")

choice = input("Enter 1 or 2")

if choice == '1':
    c = float(input("Enter temperature in Celcius"))
    f = celcius_to_fahrenheit(c)
    print(f"{c} C = {f} F")

elif choice == '2':
    f = float(input("Enter temperature in fahrenheit"))
    c = fahrenheit_to_celcius(f)
    print(f"{f} F = {c} C")

else:
    print("Invalid Choice")

Temperature Converter
1.Celcius to fahrenheit
2.Fahrenheit to celcius
26.0 C = 78.8 F

In [21]:
class Employee():
    def __init__(self, name, salary):
        self._name = name
        self._salary = salary

    def display(self):
        print(f'Employee: {self._name}\n salary: {self._salary}')

class Manager(Employee):
    def __init__(self, name, salary, bonus):
        super().__init__(name, salary)
        self.bonus = bonus

    def update_salary(self):
        self._salary += self.bonus

In [22]:
haseeb = Manager('Haseeb', 30000, 10000)

In [23]:
haseeb.display()

Employee: Haseeb
 salary: 30000

In [24]:
haseeb.update_salary()

In [25]:
haseeb.display()

Employee: Haseeb
 salary: 40000

In [31]:
class Student():
    def __init__(self):
        self.__grades = []

    def add_grade(self, grade):
        if 0<= grade <=100:
            self.__grades.append(grade)
        else:
            print('Invalid Value')

    def get_average(self):
        if self.__grades:
            return sum(self.__grades) / len(self.__grades)
        else:
            return 0

In [32]:
s = Student()

In [33]:
s.add_grade(72)

In [34]:
s.add_grade(82)

In [35]:
s.add_grade(92)

In [36]:
s.get_average()

82.0

In [ ]:
class Student():
    def __init__(self):
        self.__grades = []

    def add_grade(self, grade):
        if 0<= grade <=100:
            self.__grades.append(grade)
        else:
            print('Invalid Value')

    def get_average(self):
        if self.__grades:
            return sum(self.__grades) / len(self.__grades)
        else:
            return 0

In [38]:
s = Student()

In [ ]:
s.add_grade(82)

In [40]:
s.add_grade(93)

In [41]:
s.add_grade(92)

In [42]:
s.add_grade(83)

In [43]:
s.get_average()

87.5

In [1]:
num = 7/5
print(round(num))

1

In [ ]:
print(oct(23)+oct(23))

0o270o27

In [ ]:
print(~(~2))

2

In [1]:
False and not False

False

In [11]:
print('hadi' == 'hadi')

True

In [1]:
c = 'hadi'
c is 'hadi'

<>:2: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
C:\Users\AL REHMAN LAPTOPS\AppData\Local\Temp\ipykernel_9404\836142027.py:2: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
  c is 'hadi'

True

In [2]:
import numpy as np 
import pandas as pd

In [10]:
data = {
    'Students':[
        'haseeb', 'mohib', 'daniyal', 'harshil', 'hadi'
    ],
    'Marks': np.random.randint(50, 100, 5),
    'Class': ['XI'] * 5,
    'City': ['Karachi'] * 5,
    'Section': np.random.choice(['A', 'B'], 5)
}

In [11]:
df = pd.DataFrame(data)

In [12]:
df

  Students  Marks Class     City Section
0   haseeb     52    XI  Karachi       A
1    mohib     82    XI  Karachi       A
2  daniyal     55    XI  Karachi       B
3  harshil     77    XI  Karachi       A
4     hadi     57    XI  Karachi       A

In [14]:
df.shape

(5, 5)

In [15]:
df.size

25

In [16]:
df.head(3)

  Students  Marks Class     City Section
0   haseeb     52    XI  Karachi       A
1    mohib     82    XI  Karachi       A
2  daniyal     55    XI  Karachi       B

In [17]:
df.tail(2)

  Students  Marks Class     City Section
3  harshil     77    XI  Karachi       A
4     hadi     57    XI  Karachi       A

In [18]:
df.columns

Index(['Students', 'Marks', 'Class', 'City', 'Section'], dtype='object')

In [19]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Students  5 non-null      object
 1   Marks     5 non-null      int32
 2   Class     5 non-null      object
 3   City      5 non-null      object
 4   Section   5 non-null      object
dtypes: int32(1), object(4)
memory usage: 312.0+ bytes

In [22]:
df.describe()

           Marks
count   5.000000
mean   64.600000
std    13.831124
min    52.000000
25%    55.000000
50%    57.000000
75%    77.000000
max    82.000000

In [23]:
df['Students']

0     haseeb
1      mohib
2    daniyal
3    harshil
4       hadi
Name: Students, dtype: object

In [25]:
df[['Students', 'Section']]

  Students Section
0   haseeb       A
1    mohib       A
2  daniyal       B
3  harshil       A
4     hadi       A

In [26]:
df[2:4]

  Students  Marks Class     City Section
2  daniyal     55    XI  Karachi       B
3  harshil     77    XI  Karachi       A

In [32]:
df.loc[2]

Students    daniyal
Marks            55
Class            XI
City        Karachi
Section           B
Name: 2, dtype: object

In [33]:
df.iloc[3]

Students    harshil
Marks            77
Class            XI
City        Karachi
Section           A
Name: 3, dtype: object

In [34]:
df.loc[2, 'Marks']

np.int32(55)

In [35]:
df

  Students  Marks Class     City Section
0   haseeb     52    XI  Karachi       A
1    mohib     82    XI  Karachi       A
2  daniyal     55    XI  Karachi       B
3  harshil     77    XI  Karachi       A
4     hadi     57    XI  Karachi       A

In [36]:
df.iloc[2,1]

np.int32(55)

In [38]:
df.iloc[2:5, 0:3]

  Students  Marks Class
2  daniyal     55    XI
3  harshil     77    XI
4     hadi     57    XI

In [39]:
df.iloc[2:5, 0:2]

  Students  Marks
2  daniyal     55
3  harshil     77
4     hadi     57

In [44]:
import pandas as pd

data = {
    "EmpID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Ali", "Sara", "Hassan", "Fatima", "Bilal", "Ayesha", "Zain"],
    "Department": ["IT", "HR", "Finance", "IT", "Marketing", "HR", "Finance"],
    "Salary": [85000, 60000, 95000, 72000, 50000, 65000, 88000],
    "JoiningDate": pd.to_datetime([
        "2020-01-15", "2021-03-20", "2019-07-30",
        "2020-11-10", "2022-05-05", "2021-09-01", "2020-12-12"
    ]),
    "City": ["Karachi", "Lahore", "Islamabad", "Karachi", "Lahore", "Karachi", "Islamabad"],
    "Experience": [4, 2, 6, 3, 1, 2, 5]
}

df = pd.DataFrame(data)
df

   EmpID    Name Department  Salary JoiningDate       City  Experience
0    101     Ali         IT   85000  2020-01-15    Karachi           4
1    102    Sara         HR   60000  2021-03-20     Lahore           2
2    103  Hassan    Finance   95000  2019-07-30  Islamabad           6
3    104  Fatima         IT   72000  2020-11-10    Karachi           3
4    105   Bilal  Marketing   50000  2022-05-05     Lahore           1
5    106  Ayesha         HR   65000  2021-09-01    Karachi           2
6    107    Zain    Finance   88000  2020-12-12  Islamabad           5

In [45]:
df['Salary']

0    85000
1    60000
2    95000
3    72000
4    50000
5    65000
6    88000
Name: Salary, dtype: int64

In [46]:
df[['Name','Salary']]

     Name  Salary
0     Ali   85000
1    Sara   60000
2  Hassan   95000
3  Fatima   72000
4   Bilal   50000
5  Ayesha   65000
6    Zain   88000

In [47]:
df[df['Salary'] > 70000]

   EmpID    Name Department  Salary JoiningDate       City  Experience
0    101     Ali         IT   85000  2020-01-15    Karachi           4
2    103  Hassan    Finance   95000  2019-07-30  Islamabad           6
3    104  Fatima         IT   72000  2020-11-10    Karachi           3
6    107    Zain    Finance   88000  2020-12-12  Islamabad           5

In [48]:
df[(df["Salary"]>70000)&(df["Department"] == 'IT')]

   EmpID    Name Department  Salary JoiningDate     City  Experience
0    101     Ali         IT   85000  2020-01-15  Karachi           4
3    104  Fatima         IT   72000  2020-11-10  Karachi           3

In [51]:
df.sort_values('Salary', ascending=False)

   EmpID    Name Department  Salary JoiningDate       City  Experience
2    103  Hassan    Finance   95000  2019-07-30  Islamabad           6
6    107    Zain    Finance   88000  2020-12-12  Islamabad           5
0    101     Ali         IT   85000  2020-01-15    Karachi           4
3    104  Fatima         IT   72000  2020-11-10    Karachi           3
5    106  Ayesha         HR   65000  2021-09-01    Karachi           2
1    102    Sara         HR   60000  2021-03-20     Lahore           2
4    105   Bilal  Marketing   50000  2022-05-05     Lahore           1

In [54]:
df.sort_values('Name', ascending=True)

   EmpID    Name Department  Salary JoiningDate       City  Experience
0    101     Ali         IT   85000  2020-01-15    Karachi           4
5    106  Ayesha         HR   65000  2021-09-01    Karachi           2
4    105   Bilal  Marketing   50000  2022-05-05     Lahore           1
3    104  Fatima         IT   72000  2020-11-10    Karachi           3
2    103  Hassan    Finance   95000  2019-07-30  Islamabad           6
1    102    Sara         HR   60000  2021-03-20     Lahore           2
6    107    Zain    Finance   88000  2020-12-12  Islamabad           5